### ISSUE TITLE
TOPP workflow seems to stop at node 17 using example data. I attached the log file. I think it's the consensus2EDTA step. I made sure and point tot he python conversion script. Any ideas?

### ISSUE THREAD

**Issue by bsphinney** [userbz/DeMix-Q#1]
[TOPPAS_log.txt](https://github.com/userbz/DeMix-Q/files/81961/TOPPAS_log.txt)

**Comment by userbz** [comment]
I can see the output EDTA file had been generated, but it was failed when moving to the new path:

"Moving the target file 'C:\Users\phinlab\AppData\Local\Temp\2016-01-07_120938_BGEN-8827_14712_1\TOPPAS_tmp\DeMix\018_GenericWrapper_Consensus2EDTA\EToolout\JD_06232014_sample1-A.unknown_tmp87' from 'C:/Users/phinlab/AppData/Local/Temp/JD_06232014_sample1-A.edta' failed! Aborting ..."

I suggest to move the 'C:/Users/phinlab/AppData/Local/Temp/JD_06232014_sample1-A.edta’ to another place and do the XIC extraction manually using OpenMS. Otherwise, you might need to deal with the permission of writing to the temporary file location; or try run the workflow as administrator.
